"""Add network_type to device status

Revision ID: 4a5ca40f1dd7
Revises: 8224c328ee58
Create Date: 2025-12-07 20:17:31.935677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a5ca40f1dd7'
down_revision: Union[str, None] = '8224c328ee58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_statuses', sa.Column('network_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device_statuses', 'network_type')
    # ### end Alembic commands ###
