"""Add geofencing models

Revision ID: 8224c328ee58
Revises: c15ece13219f
Create Date: 2025-12-07 19:51:25.149873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8224c328ee58'
down_revision: Union[str, None] = 'c15ece13219f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geofences',
    sa.Column('geofence_id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('geofence_type', sa.Enum('CIRCLE', 'POLYGON', name='geofencetype'), nullable=False),
    sa.Column('center_latitude', sa.Float(), nullable=False),
    sa.Column('center_longitude', sa.Float(), nullable=False),
    sa.Column('radius_meters', sa.Float(), nullable=True),
    sa.Column('polygon_coordinates', sa.String(length=2000), nullable=True),
    sa.Column('alert_on_entry', sa.Boolean(), nullable=False),
    sa.Column('alert_on_exit', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.child_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('geofence_id')
    )
    op.create_index(op.f('ix_geofences_geofence_id'), 'geofences', ['geofence_id'], unique=False)
    op.create_table('geofence_events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('geofence_id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['children.child_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['geofence_id'], ['geofences.geofence_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_geofence_events_event_id'), 'geofence_events', ['event_id'], unique=False)
    op.create_index(op.f('ix_geofence_events_timestamp'), 'geofence_events', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_geofence_events_timestamp'), table_name='geofence_events')
    op.drop_index(op.f('ix_geofence_events_event_id'), table_name='geofence_events')
    op.drop_table('geofence_events')
    op.drop_index(op.f('ix_geofences_geofence_id'), table_name='geofences')
    op.drop_table('geofences')
    # ### end Alembic commands ###
