"""Initial migration

Revision ID: c15ece13219f
Revises: 
Create Date: 2025-11-01 14:23:46.205643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c15ece13219f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('parents',
    sa.Column('parent_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parent_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_parents_parent_id'), 'parents', ['parent_id'], unique=False)
    op.create_table('children',
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.parent_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('child_id')
    )
    op.create_index(op.f('ix_children_child_id'), 'children', ['child_id'], unique=False)
    op.create_index(op.f('ix_children_device_id'), 'children', ['device_id'], unique=True)
    op.create_table('emergency_contacts',
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['parents.parent_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('contact_id')
    )
    op.create_index(op.f('ix_emergency_contacts_contact_id'), 'emergency_contacts', ['contact_id'], unique=False)
    op.create_table('device_statuses',
    sa.Column('device_id', sa.String(length=255), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('battery_level', sa.Integer(), nullable=True),
    sa.Column('network_status', sa.String(length=50), nullable=True),
    sa.Column('app_status', sa.String(length=50), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.child_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('device_id'),
    sa.UniqueConstraint('child_id')
    )
    op.create_index(op.f('ix_device_statuses_device_id'), 'device_statuses', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_statuses_last_update'), 'device_statuses', ['last_update'], unique=False)
    op.create_table('location_histories',
    sa.Column('history_id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.child_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('history_id')
    )
    op.create_index(op.f('ix_location_histories_end_date'), 'location_histories', ['end_date'], unique=False)
    op.create_index(op.f('ix_location_histories_history_id'), 'location_histories', ['history_id'], unique=False)
    op.create_index(op.f('ix_location_histories_start_date'), 'location_histories', ['start_date'], unique=False)
    op.create_table('locations',
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.child_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.create_index('idx_location_child_timestamp', 'locations', ['child_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_locations_location_id'), 'locations', ['location_id'], unique=False)
    op.create_index(op.f('ix_locations_timestamp'), 'locations', ['timestamp'], unique=False)
    op.create_table('shake_detectors',
    sa.Column('detector_id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('sensitivity', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.child_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('detector_id'),
    sa.UniqueConstraint('child_id')
    )
    op.create_index(op.f('ix_shake_detectors_detector_id'), 'shake_detectors', ['detector_id'], unique=False)
    op.create_table('alerts',
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('alert_type', sa.Enum('SHAKE_TRIGGER', 'SOS_BUTTON', name='alerttype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'ACKNOWLEDGED', name='alertstatus'), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.Column('child_name', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['children.child_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.location_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_index(op.f('ix_alerts_alert_id'), 'alerts', ['alert_id'], unique=False)
    op.create_index(op.f('ix_alerts_timestamp'), 'alerts', ['timestamp'], unique=False)
    op.create_table('alert_distributions',
    sa.Column('distribution_id', sa.UUID(), nullable=False),
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.alert_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('distribution_id'),
    sa.UniqueConstraint('alert_id')
    )
    op.create_index(op.f('ix_alert_distributions_distribution_id'), 'alert_distributions', ['distribution_id'], unique=False)
    op.create_table('alert_distribution_contacts',
    sa.Column('distribution_id', sa.UUID(), nullable=True),
    sa.Column('contact_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['emergency_contacts.contact_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['distribution_id'], ['alert_distributions.distribution_id'], ondelete='CASCADE')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert_distribution_contacts')
    op.drop_index(op.f('ix_alert_distributions_distribution_id'), table_name='alert_distributions')
    op.drop_table('alert_distributions')
    op.drop_index(op.f('ix_alerts_timestamp'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_shake_detectors_detector_id'), table_name='shake_detectors')
    op.drop_table('shake_detectors')
    op.drop_index(op.f('ix_locations_timestamp'), table_name='locations')
    op.drop_index(op.f('ix_locations_location_id'), table_name='locations')
    op.drop_index('idx_location_child_timestamp', table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_location_histories_start_date'), table_name='location_histories')
    op.drop_index(op.f('ix_location_histories_history_id'), table_name='location_histories')
    op.drop_index(op.f('ix_location_histories_end_date'), table_name='location_histories')
    op.drop_table('location_histories')
    op.drop_index(op.f('ix_device_statuses_last_update'), table_name='device_statuses')
    op.drop_index(op.f('ix_device_statuses_device_id'), table_name='device_statuses')
    op.drop_table('device_statuses')
    op.drop_index(op.f('ix_emergency_contacts_contact_id'), table_name='emergency_contacts')
    op.drop_table('emergency_contacts')
    op.drop_index(op.f('ix_children_device_id'), table_name='children')
    op.drop_index(op.f('ix_children_child_id'), table_name='children')
    op.drop_table('children')
    op.drop_index(op.f('ix_parents_parent_id'), table_name='parents')
    op.drop_table('parents')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
